packages:
  # all packages in direct subdirs of packages/
  - '.'
  # all packages in subdirs of components/
  - 'examples/**'

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@sanity/*'
  - '@portabletext/*'
  - 'react-rx'
  - 'use-effect-event'
  - 'groq-js'
