packages:
  # all packages in direct subdirs of packages/
  - '.'
  # all packages in subdirs of components/
  - 'examples/**'

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@sanity/*'
  - 'groq-js'
  # Renovate security update: lodash@4.17.23
  - lodash@4.17.23
