packages:
  # all packages in direct subdirs of packages/
  - '.'
  # all packages in subdirs of components/
  - 'examples/**'

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@sanity/*'
  - 'groq-js'
