packages:
  # all packages in direct subdirs of packages/
  - '.'
  # all packages in subdirs of components/
  - 'examples/**'

allowBuilds:
  esbuild: false

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@sanity/*'
  - 'groq-js'
  # Renovate security update: lodash@4.18.1
  - lodash@4.18.1
